name: "darthotel"
version: "1.0.0"
author: "Barbarosa Software Ltd"
dependencies:
  react: "0.7.3"
  mustache: "0.2.3"
  path: "1.3.6"
  json_object: "1.0.18"
  browser: "0.10.0+2"
  shelf_static: "0.2.3"