name: "darthotel"
version: "1.0.0"
description: >
 A basic application displaying hotels with filters and sorting
 using react-dart and shelf + mustache to render isomorphic react components
 (both component for the client and server).
author: "Barbarosa Software Ltd <hello@barbarosa.software>"
homepage: "https://github.com/barbarosa/darthotel"
environment:
 sdk: ">=1.1.0 <2.0.0"
dependencies:
  react: "0.7.3"
  mustache: "0.2.3"
  path: "1.3.6"
  json_object: "1.0.18"
  browser: "0.10.0+2"
  shelf_static: "0.2.3"
